onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@prisma/client'
  - '@prisma/engines'
  - bufferutil
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - utf-8-validate

packages:
  - 'sdks/javascript'
